package com.example.harish.contactview.Model;


import java.io.Serializable;

/**
 * The Friend class has the data structure for creating the friend List.
 * Friends details are specified in the model.
 *
 * @author Harish Narayanasamy
 * @version 1.0
 * @since 2017-08-20
 */

public class Friend implements Serializable {


    public String name;
    //name of friend
    public String email;
    //email of friend
    public String id;
    //unique Id generated by friend
    public String bday;
    //birthday updated from listview.


    public String getName() {
        return name;
    }


    public void setBday(String bday) {
        this.bday = bday;
    }


    public Friend(String name, String email, String id, String bday) {
        this.name = name;
        this.email = email;
        this.id = id;
        this.bday = bday;

    }


}